apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-alibaba
  namespace: kube-system
type: Opaque
stringData:
  accessKeyID: << ALIBABA_ACCESS_KEY_ID >>
  accessKeySecret: << ALIBABA_ACCESS_SECRET >>
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: alibaba-machinedeployment
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
          cloudProvider: "alibaba"
          cloudProviderSpec:
            # If empty, can be set via ALIBABA_ACCESS_KEY_ID env var
            accessKeyID:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-alibaba
                key: accessKeyID
            accessKeySecret:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-alibaba
                key: accessKeySecret
            instanceType: "ecs.t1.xsmall"
            instanceName: "alibaba-instance"
            internetMaxBandwidthOut: 10
            regionID: eu-central-1
            vSwitchID: "vswitchID"
            zoneID: eu-central-1a
            diskType: "cloud_efficiency"
            diskSize: "40"
          operatingSystem: "ubuntu"
          operatingSystemSpec:
            distUpgradeOnBoot: false
            disableAutoUpdate: true
      versions:
        kubelet: 1.22.5
