apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: anexia-machinedeployment
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: anexia-machinedeployment
  template:
    metadata:
      labels:
        name: anexia-machinedeployment
    spec:
      providerSpec:
        value:
          cloudProvider: anexia
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
          cloudProviderSpec:
            # If empty, can be set via ANXCLOUD_TOKEN env var
            token:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-anexia
                key: token
            vlanID: "<< ANEXIA_VLAN_ID >>"
            # Currently only the "Flatcar Linux Stable" template is supported.
            # Use templateBuild to specify a build. If empty => latest
            # Alternatively use templateID for a specific template.
            template: "<< ANEXIA_TEMPLATE_NAME >>"
            locationID: "<< ANEXIA_LOCATION_ID >>"
            cpus: 2
            memory: 2048

            # only a single disk is currently supported, but support for multiple disks is planned already
            disks:
            - size: 60
              performanceType: ENT6

            # You may have this old disk config attribute in your config - please migrate to the disks attribute.
            # For now it is still recognized though.
            #diskSize: 60
          # Flatcar is the only supported operating system
          operatingSystem: "flatcar"
          operatingSystemSpec:
            # Force cloud-init instead of ignition. Anexia supports cloud-init only.
            provisioningUtility: "cloud-init"
            distUpgradeOnBoot: false
            disableAutoUpdate: true
      versions:
        kubelet: 1.22.5
