apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-digitalocean
  namespace: kube-system
type: Opaque
stringData:
  token: << DIGITALOCEAN_TOKEN >>
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: digitalocean-machinedeployment
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
          cloudProvider: "digitalocean"
          cloudProviderSpec:
            # If empty, can be set via DO_TOKEN env var
            token:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-digitalocean
                key: token
            region: fra1
            size: 2gb
            backups: false
            ipv6: false
            private_networking: true
            # Monitoring must be turned off for Flatcar Container Linux
            monitoring: false
            tags:
              - "machine-controller"
          # Can be 'ubuntu' or 'centos'
          operatingSystem: "ubuntu"
          operatingSystemSpec:
            disableAutoUpdate: true
      versions:
        kubelet: 1.22.5
