apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-hetzner
  namespace: kube-system
type: Opaque
stringData:
  token: << HETZNER_TOKEN >>
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: hetzner-machinedeployment
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
          cloudProvider: "hetzner"
          cloudProviderSpec:
            # If empty, can be set via HZ_TOKEN env var
            token:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-hetzner
                key: token
            serverType: "cx21"
            # Optional
            datacenter: ""
            location: "fsn1"
            image: "ubuntu-20.04"
            # Optional: placement group prefix
            placementGroupPrefix: "<< YOUR_PLACEMENT_GROUP_PREFIX >>"
            # Optional: network IDs or names
            networks:
              - "<< YOUR_NETWORK >>"
            # Optional: firewall IDs or names
            firewalls:
              - "<< YOUR_FIREWALL >>"
            # Optional
            labels:
              my: label
          operatingSystem: "ubuntu"
          operatingSystemSpec:
            distUpgradeOnBoot: false
      versions:
        kubelet: 1.22.5
