apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-openstack
  namespace: kube-system
type: Opaque
stringData:
  identityEndpoint: << OS_AUTH_URL >>
  username: << OS_USERNAME >>
  password: << OS_PASSWORD >>
  domainName: << OS_DOMAIN_NAME >>
  tenantName: << OS_TENANT_NAME >>
  region: << OS_REGION_NAME >>
  instanceReadyCheckPeriod: << INSTANCE_READY_CHECK_PERIOD >>
  instanceReadyCheckTimeout: << INSTANCE_READY_TIMEOUT >>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-controller
  namespace: kube-system
data:
  securityGroup: external-ssh
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: openstack-machinedeployment
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
          cloudProvider: "openstack"
          cloudProviderSpec:
          # If empty, can be set via OS_AUTH_URL env var
            identityEndpoint:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-openstack
                key: identityEndpoint
          # If empty, can be set via OS_USER_NAME env var
            username:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-openstack
                key: username
          # If empty, can be set via OS_PASSWORD env var
            password:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-openstack
                key: password
          # If empty, can be set via OS_DOMAIN_NAME env var
            domainName:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-openstack
                key: domainName
          # If empty, can be set via OS_TENANT_NAME env var
            tenantName:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-openstack
                key: tenantName
            # Only required if there is more than one region to choose from
            region:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-openstack
                key: region
            image: "Ubuntu 18.04 amd64"
            flavor: "m1.small"
            rhsmOfflineToken: "<< REDHAT_SUBSCRIPTIONS_OFFLINE_TOKEN >>"
            securityGroups:
              - configMapKeyRef:
                  namespace: kube-system
                  name: machine-controller
                  key: securityGroup
            # The machine won't get a floating ip if you leave this empty
            floatingIpPool: "ext-net"
            # Only required if there is more than one AZ to choose from
            availabilityZone: ""
            # Only required if there is more than one network available
            network: ""
            # Only required if the network has more than one subnet
            subnet: ""
            # Optional, if set, the rootDisk will be a volume. If not, the rootDisk
            # will be on ephemeral storage and its size will be derived from the flavor
            rootDiskSizeGB: 20
            # the list of metadata you would like to attach to the instance
            tags:
              tagKey: tagValue
          # Can be 'ubuntu', 'coreos' or 'centos'
          operatingSystem: "ubuntu"
          operatingSystemSpec:
            distUpgradeOnBoot: true
            disableAutoUpdate: true
            # 'rhelSubscriptionManagerUser' is only used for rhel os and can be set via env var `RHEL_SUBSCRIPTION_MANAGER_USER`
            rhelSubscriptionManagerUser: "<< RHEL_SUBSCRIPTION_MANAGER_USER >>"
            # 'rhelSubscriptionManagerPassword' is only used for rhel os and can be set via env var `RHEL_SUBSCRIPTION_MANAGER_PASSWORD`
            rhelSubscriptionManagerPassword: "<< RHEL_SUBSCRIPTION_MANAGER_PASSWORD >>"
            # 'rhsmOfflineToken' if it was provided red hat systems subscriptions will be removed upon machines deletions, and if wasn't
            # provided the rhsm will be disabled and any created subscription won't be removed automatically
            rhsmOfflineToken: "<< REDHAT_SUBSCRIPTIONS_OFFLINE_TOKEN >>"
      versions:
        kubelet: 1.9.6
