apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-vsphere
  namespace: kube-system
type: Opaque
stringData:
  password: << VSPHERE_PASSWORD >>
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: vsphere-machinedeployment
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
          cloudProvider: "vsphere"
          cloudProviderSpec:
            # Can also be set via the env var 'VSPHERE_USERNAME' on the machine-controller
            username: '<< VSPHERE_USERNAME >>'
            # Can also be set via the env var 'VSPHERE_ADDRESS' on the machine-controller
            # example: 'https://your-vcenter:8443'. '/sdk' gets appended automatically
            vsphereURL: '<< VSPHERE_ADDRESS >>'
            # Can also be set via the env var 'VSPHERE_PASSWORD' on the machine-controller
            password:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-vsphere
                key: password
            datacenter: datacenter1
            templateVMName: ubuntu-template
            # Optional: templateNetName is the name of the network the interface
            # on the template-machine is attached to, its only required if the
            # template-machine has more than one network
            templateNetName: ''
            # Optional: by default network will be picked up from the template
            vmNetName: network1
            # Optional
            folder: folder1
            cluster: cluster1
            datastore: datastore1
            # Can also be set via the env var 'VSPHERE_ALLOW_INSECURE' on the machine-controller
            allowInsecure: true
            cpus: 2
            memoryMB: 2048
            # Optional: Resize the root disk to this size. Must be bigger than the existing size
            # Default is to leave the disk at the same size as the template
            diskSizeGB: 10
          operatingSystem: "ubuntu"
          operatingSystemSpec:
            distUpgradeOnBoot: false
      versions:
        kubelet: 1.9.6
